# docker-compose.yml for Render deployment
version: "3.8"

services:
  docmost:
    image: docmost/docmost:latest
    environment:
      # These will be set in Render dashboard
      APP_URL: ${APP_URL}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      NODE_ENV: production
    ports:
      - "10000:3000"  # Render uses port 10000
    volumes:
      - docmost_storage:/app/data/storage
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru

volumes:
  docmost_storage:
  redis_data:
