version: "3.8"

services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: ${{RAILWAY_STATIC_URL}}
      APP_SECRET: ${{APP_SECRET}}
      DATABASE_URL: ${{DATABASE_URL}}
      REDIS_URL: ${{REDIS_URL}}
      NODE_ENV: production
    ports:
      - "3000"
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: ${{POSTGRES_PASSWORD}}
      PGDATA: /var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432"

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - "6379"
